# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.3.2
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        exclude: __init__.py
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
